version: "3.7"

services:
  db:
    image: postgres:10.1
    container_name: app_postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./deployments/dump/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app-network

  golang_application:
    container_name:  app_container
    build:
      context: ./
      dockerfile: ./deployments/dockerfiles/app.Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - .:/app/
    networks:
      - app-network

  phppgadmin:
    container_name: app_phppgadmin
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=postgres
    restart: unless-stopped
    ports:
      - "8087:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database_postgres:
    driver: local